### PR TITLE
Test pull requests

### PR DESCRIPTION
**Pull request by Michael-Baylis**

### CODE REVIEW

**Comment by cicsdeliverytest** [comment]
Can one of the admins verify this patch?

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by cicsdeliverytest** [comment]
Build triggered for merge commit.

**Comment by cicsdeliverytest** [comment]
Build started for merge commit.

**Comment by cicsdeliverytest** [comment]
Success

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
tested, cancelling

**Pull request closed without merging**
